### ISSUE TITLE
Slice function not working for matricies with more than 2 rows

### ISSUE THREAD

**Issue by dahous1** [BuckthornInc/matrix2d#5]
I noticed that there is an issue with the slice function. Here is my example:

```
Matrix2d m2d = Matrix2d();
var sliceArray = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [6, 7, 8, 9, 10]
  ];

  var newArray = m2d.slice(sliceArray, [0, 2], [0, 2]);
  print(newArray);
```

The expected outcome of this function would be `[[1, 2], [6, 7]]` however the result is `[[1, 2], [6, 7], [6, 7]`. It appears that the stop index for rows is not working beyond a value of 2. It does work if you slice from 0 to 1 but anything greater and it will take in all of the rows.

**Comment by NazeemNato** [comment]
Yes :)
